substitutions:
  # Set the MAC address of your device here
  mac_address: DA:5C:E9:23:1B:9C
  transmitter_id: 8YD26N
  use_alternative_bt_channel: "False"

esphome:
  name: "dexcom-example"

external_components:
  #- source: github://Fabian-Schmidt/esphome-dexcom
  #   # refresh: always
  - source:
      type: local
      path: components

esp32:
  board: esp32dev

logger:
  level: VERBOSE
  # level: DEBUG

esp32_ble_tracker:
  scan_parameters:
    interval: 10ms
    window: 10ms
    active: true

esp32_ble:

ble_client:
  - mac_address: ${mac_address}
    id: dexcom_ble_client_id

sensor:
  - platform: dexcom
    ble_client_id: dexcom_ble_client_id
    transmitter_id: ${transmitter_id}
    use_alternative_bt_channel: ${use_alternative_bt_channel}
    glucose_in_mg_dl:
      name: Glucose in mg/dl
      # expire_after: 10.5min # if using mqtt recommendation to set `expire_after` option.
    glucose_in_mmol_l:
      name: Glucose in mmol/l
      # expire_after: 10.5min # if using mqtt recommendation to set `expire_after` option.
    trend:
      name: Trend
      # expire_after: 10.5min # if using mqtt recommendation to set `expire_after` option.
    glucose_predict_in_mg_dl:
      name: Glucose predict in mg/dl
      # expire_after: 10.5min # if using mqtt recommendation to set `expire_after` option.
    glucose_predict_in_mmol_l:
      name: Glucose predict in mmol/l
      # expire_after: 10.5min # if using mqtt recommendation to set `expire_after` option.
