substitutions:
  # Set the MAC address of your device here
  mac_address: DA:5C:E9:23:1B:9C
  transmitter_id: 8YD26N
  use_alternative_bt_channel: "False"

esphome:
  name: "dexcom-example"

external_components:
  #- source: github://Fabian-Schmidt/esphome-dexcom
  #   # refresh: always
  - source:
      type: local
      path: components

esp32:
  board: esp32dev

logger:
  level: VERBOSE
  # level: DEBUG

esp32_ble_tracker:
  scan_parameters:
    interval: 10ms
    window: 10ms
    active: true # Necessary?

dexcom_ble_client:
  id: dexcom_ble_client_id
  transmitter_id: ${transmitter_id}
  use_alternative_bt_channel: ${use_alternative_bt_channel}
  # mac_address: ${mac_address}
  # on_disconnect:

sensor:
  - platform: dexcom_ble_client
    type: GLUCOSE_IN_MG_DL
    name: Glucose in mg/dl
    # expire_after: 10.5min # if using mqtt recommendation to set `expire_after` option.
  - platform: dexcom_ble_client
    type: GLUCOSE_IN_MMOL_L
    name: Glucose in mmol/l
  - platform: dexcom_ble_client
    type: GLUCOSE_TREND
    name: Glucose trend
  - platform: dexcom_ble_client
    type: GLUCOSE_PREDICT_IN_MG_DL
    name: Glucose predict in mg/dl
  - platform: dexcom_ble_client
    type: GLUCOSE_PREDICT_IN_MMOL_L
    name: Glucose predict in mmol/l
  - platform: dexcom_ble_client
    type: SENSOR_AGE
    name: Sensor age
  - platform: dexcom_ble_client
    type: SENSOR_SESSION_AGE
    name: Sensor session age
  - platform: dexcom_ble_client
    type: SENSOR_REMAINING_LIFETIME
    name: Sensor remaining lifetime
  - platform: dexcom_ble_client
    type: SENSOR_SESSION_REMAINING_LIFETIME
    name: Sensor session remaining lifetime

text_sensor:
  - platform: dexcom_ble_client
    type: STATUS
    name: Status
  - platform: dexcom_ble_client
    type: CALIBRATION_STATE
    name: Calibration state
